feat: add solhint
DeepSourceCorp/community-analyzers pull request #19
Opened 2023-12-22 11:13 UTC by eshaan-deepsource

Solhint: https://github.com/protofire/solhint

Resolves: ENG-523.

2023-12-28 12:49 UTC, srijan-deepsource commented on analyzers/solhint/.deepsource/issues/SOLHINT-W1001.toml
> +title = "Function has cyclomatic complexity `current` but allowed no more than maxcompl"
the title needs improvement.

2023-12-28 12:49 UTC, srijan-deepsource commented on analyzers/solhint/.deepsource/issues/SOLHINT-W1001.toml
> +Function has cyclomatic complexity `current` but allowed no more than maxcompl.
same here.

2023-12-28 12:49 UTC, srijan-deepsource commented on analyzers/solhint/.deepsource/issues/SOLHINT-W1004.toml
> +title = "Function body contains `count` lines but allowed no more than maxlines"
placeholders in title.

2023-12-28 12:49 UTC, srijan-deepsource commented on analyzers/solhint/.deepsource/issues/SOLHINT-W1004.toml
> +Function body contains `count` lines but allowed no more than maxlines.
same comment as above.

2024-01-10 09:51 UTC, yash-deepsource requested changes, later dismissed

2024-01-10 09:51 UTC, yash-deepsource commented on analyzers/solhint/.deepsource/analyzer/logo.svg
Let's use the icon instead of logo file here, as that's how it's primarily used in the UI. I found a link to the [PNG file](https://github.com/protofire/solhint/blob/develop/solhint-icon.png), but don't see an SVG.

2024-01-10 12:49 UTC, eshaan-deepsource commented on analyzers/solhint/.deepsource/issues/SOLHINT-W1001.toml
> +title = "Function has cyclomatic complexity `current` but allowed no more than maxcompl"
Discussed offline. Not changing this rn.

2024-01-11 09:21 UTC, srijan-deepsource approved these changes

2024-01-11 09:22 UTC, merged