feat: add cfn-lint
DeepSourceCorp/community-analyzers pull request #8
Opened 2023-10-27 10:42 UTC by vishnu-deepsource

2023-10-27 11:45 UTC, srijan-deepsource requested changes
I see that a good number of titles are in title-case. We use sentence-case for titles. Can you please take care of them?

Also, add a test for cfn lint's sarif file to make sure our sarif-parser works properly with this.
Ref: https://github.com/DeepSourceCorp/community-analyzers/tree/master/tests

2023-10-27 11:45 UTC, srijan-deepsource commented on analyzers/cfn-lint/.deepsource/analyzer/example_config.toml
> +name = "cfn-lint"
```suggestion
name = "cfn-lint"
type = "community"
```

2023-10-27 11:45 UTC, srijan-deepsource commented on analyzers/cfn-lint/.deepsource/analyzer/issues/CFLIN-E0002.toml
issues folder should be outside. `.deepsource/issues`

2023-10-27 11:45 UTC, srijan-deepsource commented on analyzers/cfn-lint/utils/issue_gen.py
> +    rules_directory = "./cfn-lint/src/cfnlint/rules"
Remove hardcoded values? We can take this in as input.

2023-10-27 11:45 UTC, srijan-deepsource commented on analyzers/cfn-lint/.deepsource/analyzer/issues/CFLIN-W8001.toml
> +title = "Check if Conditions are Used"
```suggestion
title = "Unused conditions detected"
```

2023-10-27 11:45 UTC, srijan-deepsource commented on analyzers/cfn-lint/.deepsource/analyzer/issues/CFLIN-W8003.toml
> +title = "Fn::Equals will always return true or false"
```suggestion
title = "`Fn::Equals` will always return true or false"
```

2023-11-30 07:05 UTC, eshaan-deepsource commented on analyzers/cfn-lint/CI/github-actions.yaml
> +          ./bin/deepsource report --analyzer cfn-lint --value-file ./cfn-lint.sarif
```suggestion
          ./bin/deepsource report --analyzer cfn-lint --analyzer-type community --value-file ./cfn-lint.sarif
```

2023-11-30 07:10 UTC, eshaan-deepsource commented on analyzers/cfn-lint/.deepsource/issues/CFLIN-E0002.toml
> +title = "error processing rule on the template"
Let's make all the titles capitilized.

2023-11-30 07:17 UTC, eshaan-deepsource commented
Can you add an entry for cfn-lint in the [README.md](https://github.com/DeepSourceCorp/community-analyzers?tab=readme-ov-file#supported-analyzers) as well?

2023-11-30 07:21 UTC, eshaan-deepsource approved these changes

2023-11-30 12:41 UTC, merged